name: GitHub Actions Deploy Game Server
run-name: ${{ github.actor }} is deploying the game server onto AWS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-server:
    name: pulumi on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Deploy AWS server with Pulumi
        run: |
          python -VV
          python Pulumi/__main__.py
